### ISSUE TITLE
Feature request: standalone mode

### ISSUE THREAD

**Issue by mlopatkin** [Grigory-Rylov/android-instrumental-test-runner-core#16]
In some environments it is beneficial to have the ability to run tests without gradle driving them. Would it be possible to add "standalone tool" mode, like the one in Spoon: to run tests from command-line, given already built test apk.

Shipping this mode as uberjar (aka fatjar) would also be helpful.

**Comment by Grigory-Rylov** [comment]
Created standalone runner core. Gradle-plugin version moved to https://github.com/Grigory-Rylov/android-instrumental-test-runner
