### ISSUE TITLE
SingleInstrumentalTestCommand goes nuts if it's created with an empty test plan list.

### ISSUE THREAD

**Issue by Jeffset** [Grigory-Rylov/android-instrumental-test-runner-core#24]
Let's consider following code from `SingleInstrumentalTestCommand`:
```
private void initTargetTestArgs(List<TestPlanElement> testForExecution) {
        StringBuilder sbClass = new StringBuilder();
        StringBuilder sbPackage = new StringBuilder();
        for (int i = 0; i < testForExecution.size(); i++) {
            TestPlanElement plan = testForExecution.get(i);
            if (plan.isPackage()) {
                if (sbPackage.length() > 0) {
                    sbPackage.append(",");
                }
                sbPackage.append(plan.getAmInstrumentCommand());
                continue;
            }

            if (sbClass.length() > 0) {
                sbClass.append(",");
            }
            sbClass.append(plan.getAmInstrumentCommand());
        }

        if (sbClass.length() > 0) {
            instrumentationArgs.put(CLASS, sbClass.toString());
        }
        if (sbPackage.length() > 0) {
            instrumentationArgs.put(PACKAGE, sbPackage.toString());
        }
    }
```
if `sbClass` and `sbPackage` are empty for some reason (e. g. if `testForExecution` is for some reason is empty) then `instrumentalArgs` will not contain test filter at all, and we might expect that runner is not going to run anything, but actually if the filter is missing instrumentation will run **every test**, so hence those weird errors with tablet tests on phones...

So I see two ways of solving this problem:
1. To make the command do nothing if test plan is empty. Maybe log a warning or something.
2. Forbid passing empty plan explicitly, e.g. throw an exception.
No doubt that if caller is creating command with an empty plan that's not good, yet our business here is to handle such case properly.

**Comment by Grigory-Rylov** [comment]
SingleInstrumentalTestCommand throws `IllegalArgumentException` if args is empty
