### ISSUE TITLE
Add gradle task for generation list of all instrumentation tests with annotation

### ISSUE THREAD

**Issue by Grishberg** [Grigory-Rylov/android-instrumental-test-runner-core#38]
Add gradle task for generation list of all instrumentation tests with annotation

**Comment by Nexen23** [comment]
Will it be really that useful? Also it seems hard to do, because we have parameters in annotations, where `@Foo(value=bar)` and `@Foo(value=nonbar)` can be completely different

**Comment by Grishberg** [comment]
better use https://github.com/linkedin/dex-test-parser without installing test apk to emulator
